name: Java CI with Gradle
on: [push, pull_request]

jobs:
  build:
    # Only run on PRs if the source branch is on someone else's repo
    if: "${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          check-latest: true
      - name: Build with Gradle
        run: ./gradlew build test --stacktrace
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: jars
          if-no-files-found: error
          path: |
            build/libs/*.jar
            !build/libs/*-unshaded.jar
